# This is a basic workflow to help you get started with Actions

name: StarRail

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]
  schedule:
    - cron: '0 21  * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy-pypi:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    environment:
      name: pypi
      url: https://pypi.org/p/hoyo-daily-logins-helper
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
      - name: Build package
        run: |
          pip install build
          make build
      - name: Publish package to pypi
        uses: pypa/gh-action-pypi-publish@release/v1
        
      - name: Daily
        run: HOYO_LANGUAGE=zh-cn hoyo-daily-logins-helper --cookie="${{ secrets.HOYO_COOKIE }}" --starrail  &> output.log
      
